### PR TITLE
Allow Start URL to be a local address

### PR DESCRIPTION
**Pull request by 3flex**
Set allowLocal to 'true' to allow private and local network IPs.

### CODE REVIEW

**Comment by sigu** [comment]
If this works, Please merge it. I really need it to work

**Comment by webdevsega** [comment]
+1

**Comment by jwillmer** [comment]
@sigu You can get it from my fork: https://github.com/jwillmer/web-scraper-chrome-extension

This is how you can use it (since it is not in the web store): [Load the extension](https://developer.chrome.com/extensions/getstarted#unpacked)

**Comment by 3flex** [comment]
@martinsbalodis this PR has been open for a long time, will it be merged? I saw some activity on the repository in May so assuming this project isn't dead though there hasn't been much activity lately.

**Comment by jwillmer** [comment]
@3flex I merged every open pull request in my fork. The author of this project is telling since 2 years (on various issues) that he will continue at some point.

**Pull request closed without merging**
